name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: prepare-packages
      run: sudo apt-get install fakeroot acl libacl1-dev attr libattr1-dev liblz4-dev libzstd-dev libxxhash-dev python3-cmarkgfm
    - name: add other-filesystem tmp dir
      run: mkdir -m 1777 /run/shm/tmp
    - name: prepare-source
      run: ./prepare-source
    - name: configure
      run: ./configure --with-included-popt --with-protected-args --with-included-zlib --enable-simd
    - name: make
      run: make
    - name: version-summary
      run: ./rsync --version
    - name: make check
      run: make check
    - name: make check30
      run: make check30
    - name: make check29
      run: make check29
