name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: prepare-source
      run: ./prepare-source
    - name: configure
      run: ./configure --with-included-popt --with-protected-args --with-included-zlib --enable-simd
    - name: make
      run: make
    - name: make check
      run: make check
