name: cygwin-save

on:
  push:
    branches: [ master ]
    paths: [ .github/workflows/cygwin-save.yml ]

jobs:

  save-artifact:
    runs-on: windows-latest
    steps:
    - uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install -y --no-progress cygwin cyg-get
    - name: prep
      run: cyg-get make autoconf automake gcc-core gcc-g++ libssl-devel libzstd-devel liblz4-devel
    - uses: actions/upload-artifact@v2
      with:
        name: tools-cygwin
        path: /tools/cygwin
